# Populate config dict from env vars
basic:
  DOWNLOAD_URL: <% ENV[DOWNLOAD_URL] %>
  UPLOAD_URL: <% ENV[UPLOAD_URL] %>

postgres:
  drivername: postgresql+psycopg2
  host: <% ENV[POSTGRES_HOST] %>
  port: <% ENV[POSTGRES_PORT] %>
  database: <% ENV[POSTGRES_DB] %>
  username: <% ENV[POSTGRES_USERNAME] %>
  password: <% ENV[POSTGRES_PASSWORD] %>
